aliyun:
    oss:
        access-id: 123
        accessKey-Secret: 321
        bucket-name: 123
        endpoint: oss-cn-chengdu.aliyuncs.com
#异步线程池
async:
    executor:
        thread:
            core_pool_size : 10
            max_pool_size : 50
            queue_capacity : 1000
            keep_alive_seconds : 300
